package com.reconlens.export;

import com.reconlens.model.EndpointGroup;
import com.reconlens.model.ParamFinding;
import com.reconlens.model.Severity;
import com.reconlens.model.TrafficEntry;
import com.reconlens.model.VulnSuggestion;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/** Renders everything ReconLens has captured into a single, client-shareable Markdown report. */
public final class ReportExporter {

    private ReportExporter() {}

    public static String render(List<EndpointGroup> groups, List<TrafficEntry> allEntries) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ReconLens Triage Report\n\n");
        sb.append("Generated: ").append(OffsetDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME)).append("\n\n");
        sb.append("Total requests captured: ").append(allEntries.size()).append("  \n");
        sb.append("Distinct endpoint groups: ").append(groups.size()).append("\n\n");

        long highRisk = 0;
        for (TrafficEntry e : allEntries) {
            if (e.highestParamSeverity() == Severity.HIGH || e.highestVulnConfidence() == Severity.HIGH) highRisk++;
        }
        sb.append("Entries with at least one HIGH-severity signal: ").append(highRisk).append("\n\n");

        sb.append("> **Note:** everything below is a heuristic lead generated by pattern matching on ")
          .append("parameter names, value shapes, and response headers/bodies. None of it was confirmed by ")
          .append("sending additional traffic to the target. Treat this as a prioritized worklist for manual ")
          .append("testing, not as a findings report, and only test systems you are authorized to test.\n\n");

        List<EndpointGroup> sorted = new ArrayList<>(groups);
        sorted.sort(Comparator.comparingInt((EndpointGroup g) -> g.memberIds.size()).reversed());

        sb.append("## Endpoint groups\n\n");
        for (EndpointGroup g : sorted) {
            List<TrafficEntry> members = new ArrayList<>();
            for (TrafficEntry e : allEntries) if (e.groupKey.equals(g.key)) members.add(e);
            if (members.isEmpty()) continue;

            sb.append("### `").append(g.method).append(' ').append(g.host).append(g.normalizedPath).append("`\n");
            sb.append("- Requests seen: ").append(members.size()).append("\n");

            List<String> vulnClasses = distinctSortedVulnClasses(members);
            if (!vulnClasses.isEmpty()) {
                sb.append("- Candidate vuln classes across this group: ").append(String.join(", ", vulnClasses)).append("\n");
            }
            sb.append("\n");

            TrafficEntry example = pickHighestSignalExample(members);

            if (!example.findings.isEmpty()) {
                sb.append("Highest-signal example (request #").append(example.id).append("):\n\n");
                for (ParamFinding f : example.findings) {
                    sb.append("- **[").append(f.severity).append("]** `").append(f.paramName).append("` -- ")
                      .append(f.category).append(": ").append(f.reason).append("\n");
                }
                sb.append("\n");
            }
            if (!example.suggestions.isEmpty()) {
                for (VulnSuggestion v : example.suggestions) {
                    sb.append("- **[").append(v.confidence).append("] ").append(v.vulnClass).append("** -- ")
                      .append(v.rationale).append(" _Try:_ ").append(v.testIdea).append("\n");
                }
                sb.append("\n");
            }
        }

        return sb.toString();
    }

    private static List<String> distinctSortedVulnClasses(List<TrafficEntry> members) {
        List<String> out = new ArrayList<>();
        for (TrafficEntry e : members) {
            for (VulnSuggestion v : e.suggestions) {
                if (!out.contains(v.vulnClass)) out.add(v.vulnClass);
            }
        }
        out.sort(Comparator.naturalOrder());
        return out;
    }

    private static TrafficEntry pickHighestSignalExample(List<TrafficEntry> members) {
        TrafficEntry best = members.get(0);
        int bestScore = score(best);
        for (TrafficEntry e : members) {
            int s = score(e);
            if (s > bestScore) {
                best = e;
                bestScore = s;
            }
        }
        return best;
    }

    private static int score(TrafficEntry e) {
        return e.highestParamSeverity().ordinal() + e.highestVulnConfidence().ordinal();
    }
}
